#!/usr/bin/env bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker tag $LOCAL_RUNTIME_IMAGE $DOCKER_RUNTIME_IMAGE
docker push $DOCKER_RUNTIME_IMAGE

docker tag $LOCAL_BUILDER_IMAGE $DOCKER_BUILDER_IMAGE
docker push $DOCKER_BUILDER_IMAGE